version: '3.8'

services:
  selenium-test:
    image: selenium-test
    ports:
      - "5000"
    deploy:
      replicas: 3
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - selenium-test
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
