version: '3.8'

services:
  selenium-test:
    image: selenium-test
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - selenium-test
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
